# Generated by Django 3.2 on 2022-09-07 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('cost', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('rating', models.FloatField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categorymodel')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('propagation', models.CharField(max_length=60)),
                ('plant_desc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_desc', to='product.productmodel')),
                ('plant_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_image', to='product.productmodel')),
                ('plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_name', to='product.productmodel')),
            ],
        ),
    ]
