# Generated by Django 3.2.12 on 2022-09-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantmodel',
            old_name='type',
            new_name='plant_type',
        ),
    ]
