# Generated by Django 3.2 on 2022-09-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.customer'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cartitem_name', to='product.productmodel'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_cartitem_price', to='product.productmodel'),
        ),
    ]
